source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

pod 'ObjectiveSugar', '~> 1.1.0'
pod 'Parse', '~> 1.7.2'
pod 'SDWebImage', '~> 3.7'
pod 'HexColors'
pod 'FBSDKLoginKit', '~> 4.4'
pod 'FBSDKShareKit', '~> 4.4'
pod 'FBSDKCoreKit', '~> 4.4'
pod 'DateTools', '1.4.2'
pod 'AFNetworking', '~> 2.3.1'
pod 'Toast', '~> 2.4'
pod 'Google-Maps-iOS-SDK'
